Back links on View & Edit School task pages
DFE-Digital/manage-free-school-projects pull request #202
Opened 2023-10-30 17:30 UTC by zhodges-nimble

2023-10-30 21:12 UTC, dangood84 requested changes
Almost perfect.  I believe the link text of each back link here should just read "Back" to match the links on the Dates and Edit dates pages.

Cheers,


Dan

2023-10-31 09:04 UTC, sukhybhullar-nimble requested changes
It needs to say "Back" in the prototype you can see what is needed: https://free-schools-store-prototype.herokuapp.com/beta-sprint-7/task-school-details-landing-page

2023-10-31 09:19 UTC, sukhybhullar-nimble approved these changes

2023-10-31 09:25 UTC, dangood84 approved these changes

2023-10-31 09:25 UTC, merged