Feature/create project capacity
DFE-Digital/manage-free-school-projects pull request #273
Opened 2023-11-28 08:33 UTC by jack-marshall-dfe

2023-11-28 10:01 UTC, sukhybhullar-nimble requested changes
A few comments

2023-11-28 10:01 UTC, sukhybhullar-nimble commented on Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/Capacity.cshtml.cs
> +            project.YrY6Capacity = (int)Extensions.IntegerExtensions.ToInt(YRY6Capacity);
I think this should just be int.Parse(), not sure why that extension even exists

2023-11-28 11:06 UTC, zhodges-nimble commented on Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Validators/ValidNumberAttribute.cs
> +        var valueAsString = (string)value;
Is this necessary as __maxValue_ is an int? So could just try to do `if (int.Parse(value) > _maxValue)`?

2023-11-28 11:18 UTC, sukhybhullar-nimble requested changes
Need to work on the validator

2023-11-28 11:18 UTC, sukhybhullar-nimble commented on Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Validators/ValidNumberAttribute.cs
> +        var specialCharactersRegex = new Regex(AllowSpecialCharactersPattern, RegexOptions.None, TimeSpan.FromSeconds(30));
1. This should use tryparse instead of parse as it may not be correct, if you put in "A" this will exception
2.  We should also include a min value
3. We don't need to check the regex, as if it doesn't parse into an int then it's invalid character
4. Is the error message for this correct?

Make sure you dev test this to confirm it works as you would expect

2023-11-29 10:50 UTC, sukhybhullar-nimble commented on Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Validators/ValidNumberAttribute.cs
> +            return new ValidationResult($"Please enter a valid number");
$ not needed for this string

2023-11-29 10:51 UTC, merged