Feature/specialist resource provision
DFE-Digital/manage-free-school-projects pull request #470
Opened 2024-03-18 09:38 UTC by jack-nimbleapproach

2024-03-25 12:05 UTC, mikestock-nimble requested changes

2024-03-25 12:07 UTC, mikestock-nimble commented
I tested it manually and there are a few issues with swapping between the school types

- On check your answers if you select the alternative provisions options, then immediately edit class type directly, you cannot select alternative provisions again
- If you switch between the school types in the school types task, it doesn't repopulate the alternative provision options and gives a validation error when trying to submit, not sure how we fix this with the current design though

2024-03-25 12:11 UTC, mikestock-nimble commented
Cpyress tests will break when this is submitted

2024-03-26 15:47 UTC, sukhybhullar-nimble approved these changes

2024-03-26 15:51 UTC, merged