Updated contact email validation and cypress tests
DFE-Digital/manage-free-school-projects pull request #571
Opened 2024-05-14 10:47 UTC by jack-nimbleapproach

2024-05-14 12:45 UTC, sukhybhullar-nimble requested changes
Just remove usings

2024-05-14 12:45 UTC, sukhybhullar-nimble commented on Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Contacts/EditContactPage.cshtml.cs
> +        if (!IsInternalEmailValid(ContactEmail) && internalContactTypes.Contains(ContactType))
Just an if statement 😜

2024-05-14 12:45 UTC, sukhybhullar-nimble commented on Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Contacts/EditContactPage.cshtml.cs
> +using DocumentFormat.OpenXml.EMMA;
usings shouldnt be here

2024-05-15 14:46 UTC, dangood84 approved these changes

2024-05-15 14:47 UTC, dangood84 approved these changes

2024-05-15 14:48 UTC, merged